ExB support
vertigis/workflow-activities-utility-network pull request #29
Opened 2023-01-05 16:53 UTC by cdoak-gh

2023-01-06 05:40 UTC, rcooney requested changes

2023-01-06 05:40 UTC, rcooney commented on src/activities/Sketch.ts
> +                if (event.state === "complete") {
This should `reject` or `resolve(undefined)`  if `event.state === "cancel"`

2023-01-06 05:40 UTC, rcooney commented on src/activities/Sketch.ts
> +    mapView: MapView;
Why a `MapView` input instead of using the `MapProvider` pattern we use elsewhere?

2023-01-06 05:40 UTC, rcooney commented on src/activities/utils.ts
> +                    if (networkGraphic.traceLocations.length == 1) {
What's this for? Why does having exactly one location make it "selected"? That seems like more of a concern of the workflow using it and not something meaningful to the activity pack.

2023-01-06 05:40 UTC, rcooney commented on src/activities/Sketch.ts
> +import SketchViewModel from "esri/widgets/Sketch/SketchViewModel";
We should be using `@arcgis/core` imports rather than `esri` ones.

2023-01-06 19:59 UTC, cdoak-gh commented on src/activities/RunUtilityNetworkTrace.ts
> +        const traceWrapper =
Done.

2023-01-06 19:59 UTC, cdoak-gh commented on src/activities/utils.ts
> +    const project =
I like this better. Done.

2023-01-06 20:02 UTC, cdoak-gh commented on src/activities/Sketch.ts
> +import type { IActivityHandler } from "@geocortex/workflow/runtime";
Should we create an activity pack just for this?  Seems like over-kill but it might be a useful repo for other similar activities.  You could argue that it should be in Core but it's also very specific since you can do this through commands and Web and Mobile.

2023-01-06 20:02 UTC, cdoak-gh commented on src/activities/Sketch.ts
> +                if (event.state === "complete") {
Done.

2023-01-06 20:03 UTC, cdoak-gh commented on src/activities/Sketch.ts
> +    mapView: MapView;
Because....bees? I forgot about the pattern.  It's fixed now.

2023-01-06 20:03 UTC, cdoak-gh commented on src/activities/utils.ts
> +                    if (networkGraphic.traceLocations.length == 1) {
Busted.  It was just easier there.  I moved it back into the workflow.

2023-01-06 20:04 UTC, cdoak-gh commented on src/activities/Sketch.ts
> +import SketchViewModel from "esri/widgets/Sketch/SketchViewModel";
Fixed.

2023-01-17 21:13 UTC, rcooney commented on src/activities/utils.ts
> +                    if (networkGraphic.traceLocations.length == 1) {
We should also remove the `selectedTraceLocation` property from the `NetworkGraphic` interface on `utils.ts` line 38. Nothing in this activity pack uses it. If the workflow wants to keep track of such a thing it is free to do so, but we don't need to supply an interface for it..

2023-01-17 21:16 UTC, rcooney commented on src/activities/Sketch.ts
> +import type { IActivityHandler } from "@geocortex/workflow/runtime";
Yes, I'd like to pull this out into a new `workflow-activities-arcgis-core` activity pack that can hold this and other general purpose ArcGIS 4.x JSAPI activities. I can help get that started.

2023-01-19 00:21 UTC, rcooney requested changes

2023-01-19 00:21 UTC, rcooney commented on src/activities/GeometryEngine.ts
> +export async function intersect(
Can we structure all these wrappers something more like this so that we preserve the Esri typings and don't need the extra `Promise` wrapper?
```
export async function intersect(
    geometry1: Geometry,
    geometry2: Geometry
): Promise<Geometry> {
    if (geometryEngine.intersect) {
        return geometryEngine.intersect(geometry1, geometry2);
    } else {
        return (geometryEngine as any).default.intersect(geometry1, geometry2);
    }
}
```

2023-01-19 00:21 UTC, rcooney commented on src/activities/GeometryEngine.ts
> +import * as geometryEngine from "@arcgis/core/geometry/geometryEngineAsync";
we should name this `geometryEngineAsync` rather than `geometryEngine` if that is what we are importing

2023-01-19 00:21 UTC, rcooney commented on src/activities/GeometryEngine.ts
> +/**
This file name should be `geometryEngineAsync.ts`. The convention is to use camelCase for file names when they don't represent a class.

2023-01-19 00:21 UTC, rcooney commented on src/activities/GeometryEngine.ts
> +/**
Same goes for `projection.ts`

2023-01-19 00:21 UTC, rcooney commented on src/activities/utils.ts
> +            layers.addMany(tables);
This is modifying `map.layers` which we probably don't want to do. Maybe...
```
for (const layer of [...layers, ...tables]) {
```

2023-01-19 00:59 UTC, cdoak-gh commented on src/activities/ValidateNetworkTopology.ts
> +    /** Perform the execution logic of the activity. */
Done

2023-01-19 00:59 UTC, cdoak-gh commented on src/activities/ValidateNetworkTopology.ts
> + * @displayName ValidateNetworkTopology
done.

2023-01-19 01:00 UTC, cdoak-gh commented on src/activities/ValidateNetworkTopology.ts
> +        const url = `${normalizedUrl}\\findDiagramInfos`;
removed the normalizedURL and findDiagrams artifact

2023-01-19 01:27 UTC, cdoak-gh commented on src/activities/ValidateNetworkTopology.ts
> +    async?: boolean;
Fixed

2023-01-19 01:27 UTC, cdoak-gh commented on src/activities/ValidateNetworkTopology.ts
> +        const options: any = {
Fixed

2023-01-19 20:36 UTC, cdoak-gh commented on src/activities/utils.ts
> +            layers.addMany(tables);
Done

2023-01-19 20:36 UTC, cdoak-gh commented on src/activities/GeometryEngine.ts
> +/**
Done

2023-01-19 20:36 UTC, cdoak-gh commented on src/activities/GeometryEngine.ts
> +import * as geometryEngine from "@arcgis/core/geometry/geometryEngineAsync";
Done

2023-01-19 20:36 UTC, cdoak-gh commented on src/activities/GeometryEngine.ts
> +export async function intersect(
Done

2023-01-19 20:40 UTC, cdoak-gh commented on src/activities/ValidateNetworkTopology.ts
> +        error: {
I check the API and you are correct, esriRequest throws an error.  I can catch that in the Workflow.

2023-01-19 22:06 UTC, rcooney requested changes

2023-01-19 22:06 UTC, rcooney commented on src/activities/ValidateNetworkTopology.ts
> +    validationSet?: any[];
This type should work
```
 { 
  sourceId: number;
  globalIds: string[];
 }[]
```

2023-01-19 22:19 UTC, cdoak-gh commented on src/activities/utils.ts
> +                        if (
Not sure what this is checking.  I use the feature layer earlier in the block so if it doesn't exist it will never get here anyway

2023-01-19 22:23 UTC, cdoak-gh commented on src/activities/utils.ts
> +                        if (
Fixed it

2023-01-19 22:24 UTC, rcooney commented on src/activities/utils.ts
> +                        if (
Correction `if (featureLayer.definitionExpression)`

2023-01-19 22:57 UTC, rcooney approved these changes

2023-01-19 23:26 UTC, merged