fix: UN trace results to layer results
vertigis/workflow-activities-utility-network pull request #35
Opened 2023-03-13 19:16 UTC by cdoak-gh

- improved performance of UN trace results to web map layer features mapping.
- cleaned up undefined checks
- improved object id and global id field lookups

2023-03-13 20:39 UTC, rcooney requested changes

2023-03-13 20:39 UTC, rcooney commented on src/activities/utils.ts
>      //Esri geodatabase fields have inconsistent case.  Find the name of the global id field regardless of case.
This comment is a bit out of date now. We are finding by type now instead.

2023-03-13 20:39 UTC, rcooney commented on src/activities/utils.ts
>                          const features = await featureLayer.queryFeatures(
Using `queryFeatureCount()` would probably be better here.

2023-03-13 20:39 UTC, rcooney commented on src/activities/utils.ts
> +            const features = await (layer as any).queryFeatures(query);
Should probably use `queryObjectIds()` and we don't need the cast `as any`

2023-03-13 20:39 UTC, rcooney commented on src/activities/utils.ts
> +                            layerSets = { ...layerSets, ...layerSet };
You can use `Object.assign(layerSets, layerSet)` to avoid redefining `layerSets` and keep it a `const`.

2023-03-13 20:39 UTC, rcooney commented on src/activities/utils.ts
> +    let layerSets = {};
Let's properly type this object and function return type.

2023-03-13 20:39 UTC, rcooney commented on src/activities/utils.ts
>  export function groupAssets(
Let's properly type this object and function return type.

2023-03-13 20:39 UTC, rcooney commented on src/activities/utils.ts
>                  typeSet = { assets: [asset] };
This line can be removed.

2023-03-13 20:39 UTC, rcooney commented on src/activities/utils.ts
> +                typeSet = { assets: [asset] };
Combine these to 
```
typeSet = {
    assets: [asset],
    layerId,
};
```

2023-03-13 20:39 UTC, rcooney commented on src/activities/utils.ts
> +                typeSet = { assets: [asset] };
How about structuring it like this?
```
const typeSet = groupSet[asset.assetTypeCode];
if (typeSet) {
    typeSet.assets.push(asset);
} else {
    const layerId = getLayerIdByDomainAndSourceId(
        parseInt(domainNetwork.domainNetworkId),
        parseInt(asset.networkSourceId),
        utilityNetwork
    );
    groupSet[asset.assetTypeCode] = {
        assets: [asset],
        layerId,
    };
}
```

2023-03-13 20:44 UTC, rcooney commented on src/activities/utils.ts
> +            const features = await (layer as any).queryFeatures(query);
We should review al the `as any` casts in this file. A number of them are not necessary anymore.

2023-03-14 22:53 UTC, cdoak-gh commented on src/activities/utils.ts
>      //Esri geodatabase fields have inconsistent case.  Find the name of the global id field regardless of case.
removed

2023-03-14 22:53 UTC, cdoak-gh commented on src/activities/utils.ts
>                          const features = await featureLayer.queryFeatures(
Yup. Much better. Fixed.

2023-03-14 22:55 UTC, cdoak-gh commented on src/activities/utils.ts
> +            const features = await (layer as any).queryFeatures(query);
changed to queryObjectIds().
I also did a thorough review of the utils functions and removed any unnecessary "any" casts and typed as many variable as was reasonable.

2023-03-14 22:55 UTC, cdoak-gh commented on src/activities/utils.ts
> +                            layerSets = { ...layerSets, ...layerSet };
Fixed

2023-03-14 22:55 UTC, cdoak-gh commented on src/activities/utils.ts
> +    let layerSets = {};
Done.

2023-03-14 22:55 UTC, cdoak-gh commented on src/activities/utils.ts
>  export function groupAssets(
Done.

2023-03-14 22:56 UTC, cdoak-gh commented on src/activities/utils.ts
> +                typeSet = { assets: [asset] };
Still need to check for undefined layerId but restructured the way you suggest.

2023-03-14 22:56 UTC, cdoak-gh commented on src/activities/utils.ts
>                  typeSet = { assets: [asset] };
Done

2023-03-15 15:51 UTC, rcooney requested changes

2023-03-15 15:51 UTC, rcooney commented on src/activities/utils.ts
> +                if (objectIds.length == assets.length) {
I don't think this `break` is working quite the way we want. This function iterates though all the feature layers/tables and queries for matching assets based on their global IDs. This `break` only bails out early if all the assets belong to the same layer. If they are on different layers it will continue to query the remaining layers unnecessarily. We should be keeping a running total of all found assets and bail when we've got them all.

Also please use `===` rather than `==` unless you are intentionally allowing for type conversions.

Maybe a question for another PR, but is there a way we can determine the Utility Network relevant feature layers from the `dataElement` so that we don't have to examine every layer in the map?

2023-03-15 16:34 UTC, cdoak-gh commented on src/activities/utils.ts
> +                if (objectIds.length == assets.length) {
I've added a counter for the break. 

For the dataElement, there's no easy way to link web map layers to trace results.  The only shared key is Layer ID, which can be repeated among a number of Web Map layers.  Until we have a global id there's no way to determine what Web Map layer a feature comes from.  We could create an activity that buckets web map layers with Utility Network Asset Types but that wouldn't be much better.

2023-03-15 17:07 UTC, rcooney approved these changes

2023-03-15 17:57 UTC, merged