fix: object id bug
vertigis/workflow-activities-utility-network pull request #37
Opened 2023-03-15 20:24 UTC by cdoak-gh

2023-03-15 22:39 UTC, rcooney requested changes

2023-03-15 22:39 UTC, rcooney commented on src/activities/utils.ts
> +            if (objectIds != null) {
Can you make this `if (objectIds)`

It does work correctly as written, but the `!= null` is a bit unclear because:
1. Are we specifically interested in checking `null` rather than `undefined` or falsey values, or was that a mistake
2. The `!=` allows for type conversion to `undefined` so it is difficult to tell if it was intentional or if it was accidental and `!==` was intended.

2023-03-15 22:46 UTC, cdoak-gh commented on src/activities/utils.ts
> +            if (objectIds != null) {
1. We are specifically interested in null.  The REST response is 
{
 "objectIdFieldName": "OBJECTID",
 "objectIds": null
}
and the returned value is null.  I've changed it to first check for undefined just in case and for clarity.
2. It was accidental and is fixed.

2023-03-16 00:20 UTC, rcooney commented on src/activities/utils.ts
> +            if (objectIds != null) {
Well the `&& objectIds !== null` is not necessary because the `if (objectIds` will be false if it is `undefined` or `null`, so we should just make it `if (objectIds)`

Also, I would not count on all versions of the JSAPI consistently returning `null` compared to `undefined` for something like this. What we care about is that `objectIds` is an array, so we should only check for that.

2023-03-16 16:33 UTC, cdoak-gh commented on src/activities/utils.ts
> +            if (objectIds != null) {
gottcha. updated

2023-03-16 18:27 UTC, rcooney approved these changes

2023-03-16 20:06 UTC, merged