subtype-layer-support
vertigis/workflow-activities-utility-network pull request #40
Opened 2023-03-27 03:10 UTC by cdoak-gh

2023-04-03 17:28 UTC, rcooney requested changes

2023-04-03 21:02 UTC, cdoak-gh commented on src/activities/utils.ts
> +export async function getObjecIds(
fixed

2023-04-03 21:03 UTC, cdoak-gh commented on src/activities/GetUtilityNetworkHelper.ts
> +        ) => Promise<FeatureLayer | SubtypeGroupLayer | undefined>;
It's necessary.  I've updated the PR title.

2023-04-03 21:11 UTC, cdoak-gh commented on src/activities/SelectNetworkGraphics.ts
> +                (x as any).layer as FeatureLayer
SubtypeGroupLayer does include queryFeatures.  I set the correct type before calling the function now.

2023-04-03 21:18 UTC, cdoak-gh commented on src/activities/utils.ts
> +                            layerSets[layer.id + i.toString()] = {
The IDs are never used by the consumer.  They only used internally to ensure unique sets.  I've changed the id to be the current time in milliseconds.  This will ensure they are unique.

2023-04-03 21:24 UTC, cdoak-gh commented on src/activities/SelectNetworkGraphics.ts
> +            (g) => (g as any).layer != undefined && ((g as any).layer.type === "feature"
Nice.  Changed

2023-04-03 21:37 UTC, cdoak-gh commented on src/activities/utils.ts
> +    layer: FeatureLayer | SubtypeGroupLayer | SubtypeSublayer;
All the consumer really cares about is mapping the trace result, which only has reference to a feature service, to its corresponding layer in the Web Map.  What they do with it after that is really up to them.  In may case I'm querying the layer so I can create a selection on the map in Web. I could do something like 

export type LayerSet = {
    id: string;
    layer: FeatureLayer | SubtypeGroupLayer;
    subtTypeLayer: SubtypeSublayer,
    objectIds: number[];
};

2023-04-03 23:35 UTC, rcooney requested changes

2023-04-03 23:35 UTC, rcooney commented on src/activities/SelectNetworkGraphics.ts
> +            (g:any) => {
You need to drop this `:any`. It is killing all the typings at the top level.

2023-04-03 23:35 UTC, rcooney commented on src/activities/SelectNetworkGraphics.ts
> +            (g:any) => {
Also:
- that `.filter(Boolean)` needs to be `.filter((x): x is __esri.GraphicHit => !!x)` to do all that we want.
- `let qLyr` needs to be typed `let qLyr: SubtypeGroupLayer | FeatureLayer;` otherwise it remains an `any`

2023-04-03 23:35 UTC, rcooney commented on src/activities/utils.ts
> +                for (const layer of featureLayers) {
Something is off with our logic. The nested loops are resulting in unnecessary work. We are looping though all layers and tables to find the right type of layers and adding them to a list. Within each loop we query all the layers in the list we are building. We either need two loops, or one that queries the layer as we find it.

2023-04-03 23:35 UTC, rcooney commented on src/activities/utils.ts
> +            (x as __esri.FeatureLayer).layerId === layerId
This type of cast is a problem. It isn't typed as a `FeatureLayer`

2023-04-03 23:35 UTC, rcooney commented on src/activities/utils.ts
> +                            layerSets[layer.id + i.toString()] = {
`Date.now()` doesn't have enough resolution to be used in this way. Since we are already marking this feature as a breaking change let's change the object.

2023-04-04 00:18 UTC, cdoak-gh commented on src/activities/SelectNetworkGraphics.ts
> +            (g:any) => {
__esri.HitTestResultResults doesn't include layer or type and __esri.GraphicHit doesn't exist.  I don't think we can get around the any typing unless we create our own GraphcHit interface and use it.

2023-04-04 00:48 UTC, cdoak-gh commented on src/activities/utils.ts
> +    layer: FeatureLayer | SubtypeGroupLayer | SubtypeSublayer;
Nevermind.  I realized I was behind in my Esri JS version.

2023-04-04 03:58 UTC, cdoak-gh commented on src/activities/SelectNetworkGraphics.ts
> +            (g:any) => {
Had an older esri api.  I updated to 4.25.   Should I update the package.json and package-lock.json?

2023-04-05 00:01 UTC, cdoak-gh commented on src/activities/utils.ts
> +                for (const layer of featureLayers) {
getWebMapLayerByAsset  isn't being used.  I've removed it as groupAssetTypesByWebMapLayer is doing the work we need.  I also did a overhaul of the grouping algorithm to correct the query spamming and improve it's efficiency.

2023-04-05 00:01 UTC, cdoak-gh commented on src/activities/utils.ts
> +            (x as __esri.FeatureLayer).layerId === layerId
Fixed.

2023-04-05 04:40 UTC, rcooney requested changes

2023-04-05 04:40 UTC, rcooney commented on src/activities/utils.ts
> +                        features.map((x) => x.attributes[objectIdField.name])
This `features.map()`  duplicates line 661. Can we compute it once and reuse the result?

The same happens on line 632

2023-04-05 04:40 UTC, rcooney commented on src/activities/utils.ts
>  export async function groupAssetTypesByWebMapLayer(
This doesn't need to be exported. It is only used internally.

2023-04-05 15:35 UTC, cdoak-gh commented on README.md
> +
fixed

2023-04-05 15:35 UTC, cdoak-gh commented on src/activities/SelectNetworkGraphics.ts
> +
fixed

2023-04-05 15:35 UTC, cdoak-gh commented on src/activities/utils.ts
> +                        objectIds = updateObjectIdArray(
fixed

2023-04-05 15:35 UTC, cdoak-gh commented on src/activities/utils.ts
> +                        features.map((x) => x.attributes[objectIdField.name])
fixed

2023-04-05 15:36 UTC, cdoak-gh commented on src/activities/utils.ts
>  export async function groupAssetTypesByWebMapLayer(
fixed

2023-04-06 14:59 UTC, rcooney requested changes

2023-04-06 14:59 UTC, rcooney commented on src/activities/utils.ts
> +                    updateObjectIdArray(objectIds, objectIds);
This looks like a mistake `(objectIds, objectIds)`

2023-04-06 16:31 UTC, cdoak-gh commented on src/activities/utils.ts
> +                    updateObjectIdArray(objectIds, objectIds);
fixed

2023-04-06 17:50 UTC, rcooney approved these changes

2023-04-06 18:23 UTC, merged