feat: Create Diagram from Features
vertigis/workflow-activities-utility-network pull request #43
Opened 2023-07-21 18:03 UTC by cdoak-gh

2023-07-25 00:13 UTC, rcooney requested changes

2023-07-25 00:13 UTC, rcooney commented on src/activities/diagrams/CreateDiagramFromFeatures.ts
> +        const body: FormData = new FormData();
I assume you are using the `FormData` and `JSON.stringify` here to deal with they double parameters you were seeing?? Neither seemed to be necessary in the `FindDiagramFeatures` activity which essentially has the same inputs.

2023-08-01 16:49 UTC, cdoak-gh commented on src/activities/__tests__/CreateTraceLocation.test.ts
> +import CreateTraceLocation from "../CreateTraceLocation";
Fixed.  Also updated older classes to include a default export

2023-08-01 16:49 UTC, cdoak-gh commented on src/activities/__tests__/CreateTraceLocation.test.ts
> +import CreateTraceLocation from "../CreateTraceLocation";
fixed.

2023-08-01 16:56 UTC, cdoak-gh commented on src/activities/diagrams/CreateDiagramFromFeatures.ts
> +        const body: FormData = new FormData();
Correct.  I couldn't find a way to avoid an array being split when sent as a GET request.  Forcing a POST also seemed to be spotty unless I stringify the JSON.

2023-08-02 22:10 UTC, rcooney requested changes

2023-08-02 22:21 UTC, rcooney approved these changes

2023-08-02 22:30 UTC, merged